version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y sqlite3
  pre_build:
    commands:
      - testversion 'cleavages_data.csv' --remote 'http://clipserve.clip.ubc.ca/topfind/download' --regex 'downloads/([\d_A-Za-z]+)\.sql'
  build:
    commands:
      - echo "Running build step"
      - bash ./script.sh $TARGETVERSION
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist