version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y sqlite3
      - npm install -g hirenj/node-reciperunner
  pre_build:
    commands:
      - testversion 'topfind.json' --remote 'http://clipserve.clip.ubc.ca/topfind/download' --regex 'downloads/([\d_A-Za-z]+)\.sql'
  build:
    commands:
      - echo "Running build step"
      - bash ./script.sh $TARGETVERSION
      - mv dist/*.csv sources/
      - runrecipe --input sources --output json
      - mv json/sources_topfind.json dist/topfind.json
  post_build:
    commands:
      - echo "Skipping post_build"
artifacts:
  files:
    - dist